**Pandas Series Questions**

1. Write a Pandas program to create and display a one-dimensional array-like
object containing an array of data using Pandas module.


In [ ]:
import pandas as pd
data = [1,2,3]
one_dimensional_array = pd.Series(data)
print(one_dimensional_array)

0    1
1    2
2    3
dtype: int64


2. Write a Pandas program to convert a Panda module Series to Python list
and it's type.

In [ ]:
import pandas as pd
data = {'a':1, 'b':2, 'c':3}
pandas_series = pd.Series(data)
python_list = pandas_series.tolist()
list_type = type(python_list)
print("Pandas Series:", pandas_series)
print("\nPython List",python_list)
print(list_type)

Pandas Series: a    1
b    2
c    3
dtype: int64

Python List [1, 2, 3]
<class 'list'>


3. Write a Pandas program to add, subtract, multiple and divide two Pandas
Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]


In [ ]:
import pandas as pd
a = pd.Series([2,4,6,8,10])
b = pd.Series([1,3,5,7,9])
c = a+b
d = a-b
e = a*b
f = a/b
print(c)
print(d)
print(e)
print(f)

0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


4. Write a Pandas program to compare the elements of the two Pandas
Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [ ]:
import pandas as pd
a = pd.Series([2,4,6,8,10])
b = pd.Series([1,3,5,7,10])
comparision_result = a==b
print(comparision_result)

0    False
1    False
2    False
3    False
4     True
dtype: bool


5. Write a Pandas program to convert a dictionary to a Pandas series.

In [ ]:
import pandas as pd
dict = {'a':1, 'b':2, 'c':3}
series = pd.Series(dict)
print(dict)
print(series)

{'a': 1, 'b': 2, 'c': 3}
a    1
b    2
c    3
dtype: int64


6. Write a Pandas program to convert a NumPy array to a Pandas series.


In [ ]:
import numpy as np
import pandas as pd
num = np.array([1,2,3,4,5])
ser = pd.Series(num)
print(ser)

0    1
1    2
2    3
3    4
4    5
dtype: int64


7. Write a Pandas program to change the data type of given a column or a
Series.


In [ ]:
d1 = {'Age': [25,30,22]}
df = pd.DataFrame(d1)
df['Age'] = df['Age'].astype(float)
print(d1)
print(type(d1))
print(df)
print(type(df))

{'Age': [25, 30, 22]}
<class 'dict'>
    Age
0  25.0
1  30.0
2  22.0
<class 'pandas.core.frame.DataFrame'>


8. Write a Pandas program to convert the first column of a DataFrame as a
Series.

In [ ]:
import pandas as pd
d = {'X':[78,85,96,80,86], 'Y':[84,94,89,83,86], 'Z':[86,97,96,72,83]}
df = pd.DataFrame(d)
print(df)
s = df['X']
print(s)
print(type(s))

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83
0    78
1    85
2    96
3    80
4    86
Name: X, dtype: int64
<class 'pandas.core.series.Series'>


9. Write a Pandas program to convert a given Series to an array.

In [ ]:
data = [2,4,6,8]
ser = pd.Series(data)
print(ser)
numpy_array = ser.to_numpy()
print(numpy_array)

0    2
1    4
2    6
3    8
dtype: int64
[2 4 6 8]


10. Write a Pandas program to convert Series of lists to one Series.

In [ ]:
import pandas as pd
s = pd.Series([['red', 'blue', 'green'], ['orange', 'yellow'], ['white']])
print(s)
s = s.apply(pd.Series).stack().reset_index(drop=True)
print(s)

0    [red, blue, green]
1      [orange, yellow]
2               [white]
dtype: object
0       red
1      blue
2     green
3    orange
4    yellow
5     white
dtype: object


11. Write a Pandas program to sort a given Series.


In [ ]:
d = {'a':1, 'b':5, 'c':3}
print(d)
d2 = pd.Series(d)
sort = d2.sort_values()
print(sort)

{'a': 1, 'b': 5, 'c': 3}
a    1
c    3
b    5
dtype: int64


12. Write a Pandas program to add some data to an existing Series.

In [ ]:
new_data_append = {'d':4, 'e':6}
updated_series = d2.append(pd.Series(new_data_append))
print(updated_series)

a    1
b    5
c    3
d    4
e    6
dtype: int64


<ipython-input-22-fe96f2cd2389>:2: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  updated_series = d2.append(pd.Series(new_data_append))


13. Write a Pandas program to create a subset of a given series based on
value and condition.

In [ ]:
import pandas as pd
s = pd.Series([1,2,3,4,5,6,7,8,9,10])
print(s)
print("Subset:")
n = 7
subset = s[s > n]
print(subset)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
Subset:
7     8
8     9
9    10
dtype: int64


14. Write a Pandas program to change the order of index of a given series.


In [ ]:
new_order = ['b', 'a', 'c']
record = d2.reindex(new_order)
print(record)

b    5
a    1
c    3
dtype: int64


15. Write a Pandas program to create the mean and standard deviation of the
data of a given Series.

In [ ]:
mean_value = d2.mean()
std_dev = d2.std()
print(d2)

print("\nMean of the Series:", mean_value)
print("Standard Deviation of the Series:", std_dev)

a    1
b    5
c    3
dtype: int64

Mean of the Series: 3.0
Standard Deviation of the Series: 2.0


16. Write a Pandas program to get the items of a given series not present in
another given series.

In [ ]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([3,4,5,6,7])
noitems = s1[~s1.isin(s2)]
print(s1)
print(s2)
print(noitems)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    3
1    4
2    5
3    6
4    7
dtype: int64
0    1
1    2
dtype: int64


17. Write a Pandas program to get the items which are not common of two
given series.

In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([3,4,5,6,7])
S1 = pd.Series(np.union1d(s1, s2))
S2 = pd.Series(np.intersect1d(s1, s2))
nocommon = S1[~S1.isin(S2)]
print(s1)
print(s2)
print(nocommon)

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    3
1    4
2    5
3    6
4    7
dtype: int64
0    1
1    2
5    6
6    7
dtype: int64


18. Write a Pandas program to compute the minimum, 25th percentile,
median, 75th, and maximum of a given series.


In [ ]:
import pandas as pd
import numpy as np
num_state = np.random.RandomState(100)
num_series = pd.Series(num_state.normal(10,4,20))
print(num_series)
result = np.percentile(num_series, q=[0,25,50,75,100])
print(result)

0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64
[ 3.00093811  8.09463867 10.23353705 12.21537733 14.61214321]


19. Write a Pandas program to calculate the frequency counts of each unique
value of a given series.


In [ ]:
import pandas as pd
A = pd.Series([1,1,2,3,4,5,5])
print(A)
print(A.value_counts())

0    1
1    1
2    2
3    3
4    4
5    5
6    5
dtype: int64
1    2
5    2
2    1
3    1
4    1
dtype: int64


20. Write a Pandas program to display most frequent value in a given series
and replace everything else as 'Other' in the series.


In [ ]:
import pandas as pd
import numpy as np
num_series = pd.Series(np.random.randint(1,5,[15]))
print(num_series)
print("Top 2 Freq:0", num_series.value_counts())
result = num_series[~num_series.isin(num_series.value_counts().index[:1])] = 'Other'
print(num_series)

0     2
1     3
2     4
3     3
4     1
5     4
6     1
7     2
8     2
9     3
10    3
11    1
12    2
13    1
14    4
dtype: int64
Top 2 Freq:0 2    4
3    4
1    4
4    3
dtype: int64
0         2
1     Other
2     Other
3     Other
4     Other
5     Other
6     Other
7         2
8         2
9     Other
10    Other
11    Other
12        2
13    Other
14    Other
dtype: object


21. Write a Pandas program to find the positions of numbers that are multiples
of 5 of a given series.


In [ ]:
import pandas as pd
import numpy as np
num_series = pd.Series(np.random.randint(1,10,9))
print(num_series)
result = np.where(num_series % 5==0)
print("Positions of no. that are multiple of 5:")
print(result)

0    7
1    6
2    2
3    2
4    2
5    8
6    7
7    8
8    7
dtype: int64
Positions of no. that are multiple of 5:
(array([], dtype=int64),)


22. Write a Pandas program to extract items at given positions of a given
series.


In [ ]:
import pandas as pd
s = pd.Series(list('123456789'))
element_pos = [1,3,5,7]
print(s)
pos = s.take(element_pos)
print(pos)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: object
1    2
3    4
5    6
7    8
dtype: object


23. Write a Pandas program to get the positions of items of a given series in
another given series.


In [ ]:
import pandas as pd
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([1,3,5,7,10])
print(s1)
print(s2)
pos = [pd.Index(s1).get_loc(i) for i in s2]
print(pos)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
0     1
1     3
2     5
3     7
4    10
dtype: int64
[0, 2, 4, 6, 9]


24. Write a Pandas program convert the first and last character of each word
to upper case in each word of a given series.


In [ ]:
import pandas as pd
s = pd.Series(['world', 'peace', 'university'])
print(s)
result = s.map(lambda x: x[0].upper() +x[1:-1] + x[-1].upper())
print(result)

0         world
1         peace
2    university
dtype: object
0         WorlD
1         PeacE
2    UniversitY
dtype: object


25. Write a Pandas program to calculate the number of characters in each
word in a given series

In [ ]:
import pandas as pd
s = pd.Series(['world', 'peace', 'university'])
print(s)
result = s.map(lambda x: len(x))
print(result)

0         world
1         peace
2    university
dtype: object
0     5
1     5
2    10
dtype: int64


**Pandas DataFrame Questions**

1.Write a Pandas program to create a dataframe from a dictionary and display
it.
Sample data: {'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}


In [ ]:
import pandas as pd
sample_data = {'X':[78,85,96,80,86], 'Y':[84,94,89,83,86], 'Z':[86,97,96,72,83]}
df = pd.DataFrame(sample_data)
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


2. Write a Pandas program to create and display a DataFrame from a
specified dictionary data which has the index labels.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


3. Write a Pandas program to display a summary of the basic information
about a specified DataFrame and its data.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print(df.info())

Summary of the basic information the DataFrame and its data:
<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   name      10 non-null     object 
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64  
 3   qualify   10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes
None


4. Write a Pandas program to get the first 3 rows of a given DataFrame.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print(df.iloc[:3])

First 3 rows of the DataFrame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


5. Write a Pandas program to select the 'name' and 'score' columns from the
following DataFrame.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print(df[['name','score']])

Selecting specific columns:
        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


6. Write a Pandas program to select the specified columns and rows from a
given data frame.
Sample Python dictionary data and list labels:
Select 'name' and 'score' columns in rows 1, 3, 5, 6 from the following data
frame.
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas']

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print(df.iloc[[1,3,5,6], [1,3]])

Selecting specific rows and columns:
   score qualify
b    9.0      no
d    NaN      no
f   20.0     yes
g   14.5     yes


7. Write a Pandas program to select the rows where the number of attempts in
the examination is greater than 2.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print(df[df['attempts'] > 2])

Number of attempts in the examination is greater than 2:
      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes


8. Write a Pandas program to count the number of rows and columns of a
DataFrame.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print(df)
no_rows = len(df.index)
print(no_rows)
no_col = len(df.columns)
print(no_col)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
10
4


9. Write a Pandas program to select the rows where the score is missing, i.e.
is NaN.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print(df[df['score'].isnull()])

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no


10. Write a Pandas program to select the rows the score is between 15 and
20 (inclusive).
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print(df[df['score'].between(15,20)])

        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes


11. Write a Pandas program to select the rows where number of attempts in
the examination is less than 2 and score greater than 15.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print(df[(df['attempts'] < 2) & (df['score'] > 15)])

    name  score  attempts qualify
j  Jonas   19.0         1     yes


12. Write a Pandas program to change the score in row 'd' to 11.5.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print(df)
df.loc['d','score'] = 11.5
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


13. Write a Pandas program to calculate the sum of the examination attempts
by the students.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print(df['attempts'].sum())

19


14. Write a Pandas program to calculate the mean of all students' scores.
Data is stored in a dataframe.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print(df['score'].mean())

13.5625


15. Write a Pandas program to append a new row 'k' to data frame with given
values for each column. Now delete the new row and return the original
DataFrame.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
Values for each column will be:
name : "Suresh", score: 15.5, attempts: 1, qualify: "yes", label: "k"

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print(df)
print("\nAppend a new row:")
df.loc['k'] = ['Suresh', 15.5, 1, 'yes']
print(df)
print("\nDelete new row")
df = df.drop('k')
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

Append a new row:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
k     Suresh   15.5         1     yes

Delete new row
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima   

16. Write a Pandas program to sort the DataFrame first by 'name' in
descending order, then by 'score' in ascending order.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
Values for each column will be:
name : "Suresh", score: 15.5, attempts: 1, qualify: "yes", label: "k"

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print(df)
df = df.sort_values(by = ['name', 'score'], ascending = [False, True])
print("Sort the DataFrame first by 'name' in descending order, then by 'score' in ascending order:")
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
Sort the DataFrame first by 'name' in descending order, then by 'score' in ascending order:
        name  score  attempts qualify
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes


17. Write a Pandas program to replace the 'qualify' column contains the
values 'yes' and 'no' with True and False.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print(df)
print("Replacing 'yes' & 'no' with 'True' & 'False':")
df['qualify'] = df['qualify'].map({'yes':True, 'no':False})
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
Replacing 'yes' & 'no' with 'True' & 'False':
        name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
c  Katherine   16.5         2     True
d      James    NaN         3    False
e      Emily    9.0         2    False
f    Michael   20.0         3     True
g    Matthew   14.5         1     True
h      Laura    NaN         1    False
i      Kevin    8.0         2    False
j      Jonas   19.0         1     True


18. Write a Pandas program to change the name 'James' to 'Suresh' in name
column of the DataFrame.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print(df)
print("Replaced Name:")
df['name'] = df['name'].replace('James','Suresh')
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
Replaced Name:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d     Suresh    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


19. Write a Pandas program to delete the 'attempts' column from the
DataFrame.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print(df)
df.pop('attempts')
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
        name  score qualify
a  Anastasia   12.5     yes
b       Dima    9.0      no
c  Katherine   16.5     yes
d      James    NaN      no
e      Emily    9.0      no
f    Michael   20.0     yes
g    Matthew   14.5     yes
h      Laura    NaN      no
i      Kevin    8.0      no
j      Jonas   19.0     yes


20. Write a Pandas program to insert a new column in existing DataFrame.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print(df)
col = ['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10']
df['column'] = col
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
        name  score  attempts qualify column
a  Anastasia   12.5         1     yes     c1
b       Dima    9.0         3      no     c2
c  Katherine   16.5         2     yes     c3
d      James    NaN         3      no     c4
e      Emily    9.0         2      no     c5
f    Michael   20.0         3     yes     c6
g    Matthew   14.5         1     yes     c7
h      Laura    NaN         1      no     c8
i      Kevin    8.0         2      no     c9
j      Jonas   19.0         1     yes    c10


21. Write a Pandas program to iterate over rows in a DataFrame.
Sample Python dictionary data and list labels:
exam_data = [{'name':'Anastasia', 'score':12.5}, {'name':'Dima','score':9},
{'name':'Katherine','score':16.5}]


In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name':'Anastasia', 'score':12.5}, {'name':'Dima','score':9}, {'name':'Katherine','score':16.5}
df = pd.DataFrame(exam_data)
for index , row in df.iterrows():
  print(row['name'], row['score'])

Anastasia 12.5
Dima 9.0
Katherine 16.5


22. Write a Pandas program to get list from DataFrame column headers.
Sample Python dictionary data and list labels:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily',
'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [ ]:
import pandas as pd
import numpy as np
exam_data = {'name':['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'], 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19], 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index = labels)
print(list(list(df.columns.values)))

['name', 'score', 'attempts', 'qualify']


23. Write a Pandas program to rename columns of a given DataFrame

In [ ]:
import pandas as pd
d = {'c1':[1,2,3], 'c2':[4,5,6], 'c3':[7,8,9]}
df = pd.DataFrame(d)
print(df)
df.columns = ['col1', 'col2', 'col3']
df = df.rename(columns = {'c1':'col1', 'c2':'col2', 'c3':'col3'})
print("Renaming Columns:")
print(df)

   c1  c2  c3
0   1   4   7
1   2   5   8
2   3   6   9
Renaming Columns:
   col1  col2  col3
0     1     4     7
1     2     5     8
2     3     6     9


24. Write a Pandas program to select rows from a given DataFrame based on
values in some columns.

In [ ]:
import pandas as pd
import numpy as np
d = {'c1':[7,2,8,4,5], 'c2':[4,5,6,5,8], 'c3':[2,8,9,0,1]}
df = pd.DataFrame(d)
print(df)
print("Rows from c2 value == 5")
print(df.loc[df['c2'] == 5])

   c1  c2  c3
0   7   4   2
1   2   5   8
2   8   6   9
3   4   5   0
4   5   8   1
Rows from c2 value == 5
   c1  c2  c3
1   2   5   8
3   4   5   0


25. Write a Pandas program to change the order of a DataFrame columns.

In [ ]:
import pandas as pd
import numpy as np
d = {'c1':[7,2,8,4,5], 'c2':[4,5,6,5,8], 'c3':[2,8,9,0,1]}
df = pd.DataFrame(d)
print(df)
print("Changing the order of DataFrame:")
df = df[['c3', 'c2', 'c1']]
print(df)

   c1  c2  c3
0   7   4   2
1   2   5   8
2   8   6   9
3   4   5   0
4   5   8   1
Changing the order of DataFrame:
   c3  c2  c1
0   2   4   7
1   8   5   2
2   9   6   8
3   0   5   4
4   1   8   5


**Pandas String Operations:t**

1. Write a Pandas program to convert all the string values to upper, lower
cases in a given pandas series. Also find the length of the string values.


In [ ]:
import pandas as pd
s = pd.Series(['World', 'Peace', 'University'])
print(s)
print(s.str.upper())
print(s.str.lower())
print(s.str.len())

0         World
1         Peace
2    University
dtype: object
0         WORLD
1         PEACE
2    UNIVERSITY
dtype: object
0         world
1         peace
2    university
dtype: object
0     5
1     5
2    10
dtype: int64


2. Write a Pandas program to remove whitespaces, left sided whitespaces
and right sided whitespaces of the string values of a given pandas series.

In [ ]:
import pandas as pd
s = pd.Series(['World ', ' Peace ', ' University'])
print(s)
print(s.str.strip())
print(s.str.rstrip())
print(s.str.lstrip())

0         World 
1         Peace 
2     University
dtype: object
0         World
1         Peace
2    University
dtype: object
0          World
1          Peace
2     University
dtype: object
0        World 
1        Peace 
2    University
dtype: object


3. Write a Pandas program to add leading zeros to the integer column in a
pandas series and makes the length of the field to 8 digit.


In [ ]:
import pandas as pd
no = {'amount': [10, 100, 100, 1000]}
df = pd.DataFrame(no)
print(df)
print("\nAdd Leading Zeros;")
df['amount'] = df['amount'].apply(lambda x: '{0:0>8}'.format(x))
print(df)

   amount
0      10
1     100
2     100
3    1000

Add Leading Zeros;
     amount
0  00000010
1  00000100
2  00000100
3  00001000


4. Write a Pandas program to add leading zeros to the character column in a
pandas series and makes the length of the field to 8 digit.


In [ ]:
import pandas as pd
no = {'amount': [10, 100, 100, 1000]}
df = pd.DataFrame(no)
print(df)
print("\nAdd Leading Zeros;")
df['amount'] = df['amount'].astype(str).str.zfill(8)
print(df)

   amount
0      10
1     100
2     100
3    1000

Add Leading Zeros;
     amount
0  00000010
1  00000100
2  00000100
3  00001000


5. Write a Pandas program to capitalize all the string values of specified
columns of a given DataFrame.

In [ ]:
import pandas as pd
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit'], 'jersey': [7, 18, 45]})
print(df)
print("\nCapitalizing name column:")
df['name'] = list(map(lambda x: x.capitalize(), df['name']))
print(df)

    name  jersey
0  dhoni       7
1  virat      18
2  rohit      45

Capitalizing name column:
    name  jersey
0  Dhoni       7
1  Virat      18
2  Rohit      45


6. Write a Pandas program to count of occurrence of a specified substring in a
DataFrame column.

In [ ]:
import pandas as pd
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit'], 'jersey': [7, 18, 45]})
print(df)
print("\nCounting occurence of 't' in name column:")
df['count'] = list(map(lambda x: x.count("t"), df['name']))
print(df)

    name  jersey
0  dhoni       7
1  virat      18
2  rohit      45

Counting occurence of 't' in name column:
    name  jersey  count
0  dhoni       7      0
1  virat      18      1
2  rohit      45      1


7. Write a Pandas program to find the index of a given substring of a
DataFrame column.

In [ ]:
import pandas as pd
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit'], 'jersey': [7, 18, 45]})
print(df)
print("\nFinding the index of 'i' in name column:")
df['index'] = list(map(lambda x: x.find("i"), df['name']))
print(df)

    name  jersey
0  dhoni       7
1  virat      18
2  rohit      45

Finding the index of 'i' in name column:
    name  jersey  index
0  dhoni       7      4
1  virat      18      1
2  rohit      45      3


8. Write a Pandas program to find the index of a substring of DataFrame with
beginning and end position.

In [ ]:
import pandas as pd
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit'], 'jersey': [7, 18, 45]})
print(df)
df['index'] = list(map(lambda x: x.find("i", 0, 5), df['name']))
print(df)

    name  jersey
0  dhoni       7
1  virat      18
2  rohit      45
    name  jersey  index
0  dhoni       7      4
1  virat      18      1
2  rohit      45      3


9. Write a Pandas program to check whether alpha numeric values present in
a given column of a DataFrame.
Note: isalnum() function returns True if all characters in the string are
alphanumeric and there is at least one character, False otherwise.

In [ ]:
import pandas as pd
df = pd.DataFrame({'name': ['dhoni 07thala', 'virat', 'rohit 45'], 'jersey': [7, 18, 45]})
print(df)
print("\nWheather all characters in the string are alpha numeric:")
df['name_is_alphanumeric'] = list(map(lambda x: x.isalnum(), df['name']))
print(df)

            name  jersey
0  dhoni 07thala       7
1          virat      18
2       rohit 45      45

Wheather all characters in the string are alpha numeric:
            name  jersey  name_is_alphanumeric
0  dhoni 07thala       7                 False
1          virat      18                  True
2       rohit 45      45                 False


10. Write a Pandas program to check whether alphabetic values present in a
given column of a DataFrame.
Note: isalpha() returns True if all characters in the string are alphabetic and
there is at least one character, False otherwise.

In [ ]:
import pandas as pd
df = pd.DataFrame({'name': ['dhoni 07thala', 'virat', 'rohit 45'], 'jersey': [7, 18, 45]})
print(df)
print("\nWheather alphabetic values present in name column:")
df['name_is_alpha'] = list(map(lambda x: x.isalpha(), df['name']))
print(df)

            name  jersey
0  dhoni 07thala       7
1          virat      18
2       rohit 45      45

Wheather alphabetic values present in name column:
            name  jersey  name_is_alpha
0  dhoni 07thala       7          False
1          virat      18           True
2       rohit 45      45          False


11. Write a Pandas program to check whether only numeric values present in
a given column of a DataFrame.

In [ ]:
import pandas as pd
df = pd.DataFrame({'name': ['dhoni', '18', 'rohit'], 'jersey': [7, 18, 45]})
print(df)
print("\nWheather numeric values present in name column:")
df['name_is_digit'] = list(map(lambda x: x.isdigit(), df['name']))
print(df)

    name  jersey
0  dhoni       7
1     18      18
2  rohit      45

Wheather numeric values present in name column:
    name  jersey  name_is_digit
0  dhoni       7          False
1     18      18           True
2  rohit      45          False


12. Write a Pandas program to check whether only lower case or upper case
is present in a given column of a DataFrame.

In [ ]:
import pandas as pd
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit'], 'jersey': [7, 18, 45]})
print(df)
print("\nChecking Upper Cases")
df['name_is_upper'] = list(map(lambda x: x.isupper(), df['name']))
print(df)
print("\nChecking Lower Cases")
df['name_is_lower'] = list(map(lambda x: x.islower(), df['name']))
print(df)

    name  jersey
0  dhoni       7
1  virat      18
2  rohit      45

Checking Upper Cases
    name  jersey  name_is_upper
0  dhoni       7          False
1  virat      18          False
2  rohit      45          False

Checking Lower Cases
    name  jersey  name_is_upper  name_is_lower
0  dhoni       7          False           True
1  virat      18          False           True
2  rohit      45          False           True


13. Write a Pandas program to check whether only proper case or title case is
present in a given column of a DataFrame.


In [ ]:
import pandas as pd
df = pd.DataFrame({'name': ['Dhoni', 'virat', 'rohit'], 'jersey': [7, 18, 45]})
print(df)
print("\nChecking Title Cases")
df['name_is_title'] = list(map(lambda x: x.istitle(), df['name']))
print(df)

    name  jersey
0  Dhoni       7
1  virat      18
2  rohit      45

Checking Title Cases
    name  jersey  name_is_title
0  Dhoni       7           True
1  virat      18          False
2  rohit      45          False


14. Write a Pandas program to check whether only space is present in a given
column of a DataFrame.

In [ ]:
import pandas as pd
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit', ' '], 'jersey': [7, 18, 45, 9]})
print(df)
print("\nChecking Space")
df['name_is_title'] = list(map(lambda x: x.isspace(), df['name']))
print(df)

    name  jersey
0  dhoni       7
1  virat      18
2  rohit      45
3              9

Checking Space
    name  jersey  name_is_title
0  dhoni       7          False
1  virat      18          False
2  rohit      45          False
3              9           True


15. Write a Pandas program to get the length of the string present of a given
column in a DataFrame.


In [ ]:
import pandas as pd
df = pd.DataFrame({'name': ['Dhoni', 'virat', 'rohit'], 'jersey': [7, 18, 45]})
print(df)
print("\nGeting lenght of String")
df['name_lenght'] = df['name'].apply(len)
print(df)

    name  jersey
0  Dhoni       7
1  virat      18
2  rohit      45

Geting lenght of String
    name  jersey  name_lenght
0  Dhoni       7            5
1  virat      18            5
2  rohit      45            5


16. Write a Pandas program to get the length of the integer of a given column
in a DataFrame.

In [ ]:
import pandas as pd
df = pd.DataFrame({'name': ['Dhoni', 'virat', 'rohit'], 'jersey': [7, 18, 45]})
print(df)
print("\nGeting lenght of Integer")
df['jersey_lenght'] = df['jersey'].map(str).apply(len)
print(df)

    name  jersey
0  Dhoni       7
1  virat      18
2  rohit      45

Geting lenght of Integer
    name  jersey  jersey_lenght
0  Dhoni       7              1
1  virat      18              2
2  rohit      45              2


17. Write a Pandas program to check if a specified column starts with a
specified string in a DataFrame.


In [ ]:
import pandas as pd
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit'], 'jersey': [7, 18, 45]})
print(df)
print("\nChecking that specified Column starts with specifiedString")
df['name_lenght'] = list(map(lambda x: x.startswith('d'), df['name']))
print(df)

    name  jersey
0  dhoni       7
1  virat      18
2  rohit      45

Checking that specified Column starts with specifiedString
    name  jersey  name_lenght
0  dhoni       7         True
1  virat      18        False
2  rohit      45        False


18. Write a Pandas program to swap the cases of a specified character
column in a given DataFrame.

In [ ]:
import pandas as pd
df = pd.DataFrame({'name': ['dHONi', 'vIRAt', 'rOHIt'], 'jersey': [7, 18, 45]})
print(df)
print("\nSwapping the cases of a specified character column")
df['name_swapped'] = list(map(lambda x: x.swapcase(), df['name']))
print(df)

    name  jersey
0  dHONi       7
1  vIRAt      18
2  rOHIt      45

Swapping the cases of a specified character column
    name  jersey name_swapped
0  dHONi       7        DhonI
1  vIRAt      18        ViraT
2  rOHIt      45        RohiT


19. Write a Pandas program to convert a specified character column in
upper/lower cases in a given DataFrame.

In [ ]:
import pandas as pd
df = pd.DataFrame({'name': ['Dhoni', 'Virat', 'Rohit'], 'jersey': [7, 18, 45]})
print(df)
print("\nConverting into Upper Cases")
df['name_upper'] = list(map(lambda x: x.upper(), df['name']))
print(df)
print("\nConverting into Lower Cases")
df['name_lower'] = list(map(lambda x: x.lower(), df['name']))
print(df)

    name  jersey
0  Dhoni       7
1  Virat      18
2  Rohit      45

Converting into Upper Cases
    name  jersey name_upper
0  Dhoni       7      DHONI
1  Virat      18      VIRAT
2  Rohit      45      ROHIT

Converting into Lower Cases
    name  jersey name_upper name_lower
0  Dhoni       7      DHONI      dhoni
1  Virat      18      VIRAT      virat
2  Rohit      45      ROHIT      rohit


20. Write a Pandas program to convert a specified character column in title
case in a given DataFrame.


In [ ]:
import pandas as pd
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit'], 'jersey': [7, 18, 45]})
print(df)
print("\nChecking Title Cases")
df['name_is_title_cases'] = list(map(lambda x: x.title(), df['name']))
print(df)

    name  jersey
0  dhoni       7
1  virat      18
2  rohit      45

Checking Title Cases
    name  jersey name_is_title_cases
0  dhoni       7               Dhoni
1  virat      18               Virat
2  rohit      45               Rohit


21. Write a Pandas program to replace arbitrary values with other values in a
given DataFrame.

In [ ]:
import pandas as pd
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit'], 'jersey': [7, 18, 45]})
print(df)
print("\nReplacing I with Y")
df = list(map(lambda x: x.replace('i', 'y'), df['name']))
print(df)

    name  jersey
0  dhoni       7
1  virat      18
2  rohit      45

Replacing I with Y
['dhony', 'vyrat', 'rohyt']


22. Write a Pandas program to replace more than one value with other values
in a given DataFrame.


In [ ]:
import pandas as pd
df = pd.DataFrame({'name': ['A', 'B', 'C'], 'jersey': [7, 18, 45]})
print(df)
print("\nReplacing more than one values")
df = df.replace(["A", "C"], ["X", "Y"])
print(df)

  name  jersey
0    A       7
1    B      18
2    C      45

Replacing more than one values
  name  jersey
0    X       7
1    B      18
2    Y      45


23. Write a Pandas program to split a string of a column of a given DataFrame
into multiple columns.


In [ ]:
import pandas as pd
df = pd.DataFrame({'name': ['MS DHoni', 'Virat Kohli', 'Rohit Sharma'], 'jersey': [7, 18, 45]})
print(df)
print("\nReplacing I with Y")
df[["first", "last"]] = df["name"].str.split(" ", expand = True)
print(df)

           name  jersey
0      MS DHoni       7
1   Virat Kohli      18
2  Rohit Sharma      45

Replacing I with Y
           name  jersey  first    last
0      MS DHoni       7     MS   DHoni
1   Virat Kohli      18  Virat   Kohli
2  Rohit Sharma      45  Rohit  Sharma


24. Write a Pandas program to extract email from a specified column of string
type of a given DataFrame.

In [ ]:
import pandas as pd
import re as re
df = pd.DataFrame({'name_email': ['MS Dhoni ms@gmail.com', 'Virat Kohli', 'Rohit Sharma rohit@yahoo.com']})
print(df)
def find_email(text):
    email = re.findall(r'[\w\.-]+@[\w\.-]+',str(text))
    return ",".join(email)
df['email']=df['name_email'].apply(lambda x: find_email(x))
print("\Extracting email from dataframe columns:")
print(df)

                     name_email
0         MS Dhoni ms@gmail.com
1                   Virat Kohli
2  Rohit Sharma rohit@yahoo.com
\Extracting email from dataframe columns:
                     name_email            email
0         MS Dhoni ms@gmail.com     ms@gmail.com
1                   Virat Kohli                 
2  Rohit Sharma rohit@yahoo.com  rohit@yahoo.com


25. Write a Pandas program to extract hash attached word from twitter text
from the specified column of a given DataFrame.

In [ ]:
import pandas as pd
import re as re
df = pd.DataFrame({'tweets':['#thala for a reason','#king kohli','ro #hit man']})
print(df)
def find_hash(text):
    hword=re.findall(r'(?<=#)\w+',text)
    return " ".join(hword)
df['hash_word']=df['tweets'].apply(lambda x: find_hash(x))
print("\Extracting#word from dataframe columns:")
print(df)

                tweets
0  #thala for a reason
1          #king kohli
2          ro #hit man
\Extracting#word from dataframe columns:
                tweets hash_word
0  #thala for a reason     thala
1          #king kohli      king
2          ro #hit man       hit


**Pandas Join and Merge:**


1. Write a Pandas program to join the two given dataframes along rows and
assign all data.

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit'], 'jersey': [7, 18, 45]})
print(df1)
df2 = pd.DataFrame({'name': ['jadeja', 'devilliers', 'williamson'], 'jersey': [8, 17, 22]})
print(df2)
print("\nJoining 2 DataFrames along rows")
joined_df = pd.concat([df1, df2])
print(joined_df)

    name  jersey
0  dhoni       7
1  virat      18
2  rohit      45
         name  jersey
0      jadeja       8
1  devilliers      17
2  williamson      22

Joining 2 DataFrames along rows
         name  jersey
0       dhoni       7
1       virat      18
2       rohit      45
0      jadeja       8
1  devilliers      17
2  williamson      22


2. Write a Pandas program to join the two given dataframes along columns
and assign all data.

In [ ]:
import pandas as pd
df1 = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit'], 'jersey': [7, 18, 45]})
print(df1)
df2 = pd.DataFrame({'name': ['jadeja', 'devilliers', 'williamson'], 'jersey': [8, 17, 22]})
print(df2)
print("\nJoining 2 DataFrames along rows")
joined_df = pd.concat([df1, df2], axis = 1)
print(joined_df)

    name  jersey
0  dhoni       7
1  virat      18
2  rohit      45
         name  jersey
0      jadeja       8
1  devilliers      17
2  williamson      22

Joining 2 DataFrames along rows
    name  jersey        name  jersey
0  dhoni       7      jadeja       8
1  virat      18  devilliers      17
2  rohit      45  williamson      22


3. Write a Pandas program to append rows to an existing DataFrame and
display the combined data.

In [2]:
import pandas as pd
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit'], 'jersey': [7, 18, 45]})
print(df)
S = pd.Series(['jadeja', 8], index = ['name', 'jersey'])
print("\nNew Row")
print(S)
df1 = df.append(S, ignore_index = True)
print("\nCombined Data:")
print(df1)

    name  jersey
0  dhoni       7
1  virat      18
2  rohit      45

New Row
name      jadeja
jersey         8
dtype: object

Combined Data:
     name  jersey
0   dhoni       7
1   virat      18
2   rohit      45
3  jadeja       8


<ipython-input-2-6eca96583a60>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(S, ignore_index = True)


4. Write a Pandas program to append a list of dictioneries or series to a
existing DataFrame and display the combined data.

In [3]:
import pandas as pd
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit'], 'jersey': [7, 18, 45]})
print(df)
dicts = [{'name': 'devilliers', 'jersey': 17}, {'name': 'williamson', 'jersey': 22}]
print("\nDictionary:")
print(dicts)
df1 = df.append(dicts, ignore_index = True, sort = False)
print("\nCombined Data:")
print(df1)

    name  jersey
0  dhoni       7
1  virat      18
2  rohit      45

Dictionary:
[{'name': 'devilliers', 'jersey': 17}, {'name': 'williamson', 'jersey': 22}]

Combined Data:
         name  jersey
0       dhoni       7
1       virat      18
2       rohit      45
3  devilliers      17
4  williamson      22


<ipython-input-3-a27ba6ee3f12>:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df.append(dicts, ignore_index = True, sort = False)


5. Write a Pandas program to join the two given dataframes along rows and
merge with another dataframe along the common column id.

In [5]:
import pandas as pd
df1 = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit'], 'jersey': [7, 18, 45]})
print(df1)
df2 = pd.DataFrame({'name': ['jadeja', 'devilliers', 'williamson'], 'jersey': [8, 17, 22]})
print(df2)
df3 = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit', 'jadeja', 'devilliers', 'williamson'], 'team': ['CSK', 'RCB', 'MI', 'CSK', 'RCB', 'GT']})
print(df3)
print("\nJoining 1st DF along rows")
DF = pd.concat([df1, df2])
print(DF)
print("\nJoining DF & df3 along name")
final_data = pd.merge(DF, df3, on = 'name')
print(final_data)

    name  jersey
0  dhoni       7
1  virat      18
2  rohit      45
         name  jersey
0      jadeja       8
1  devilliers      17
2  williamson      22
         name team
0       dhoni  CSK
1       virat  RCB
2       rohit   MI
3      jadeja  CSK
4  devilliers  RCB
5  williamson   GT

Joining 1st DF along rows
         name  jersey
0       dhoni       7
1       virat      18
2       rohit      45
0      jadeja       8
1  devilliers      17
2  williamson      22

Joining DF & df3 along name
         name  jersey team
0       dhoni       7  CSK
1       virat      18  RCB
2       rohit      45   MI
3      jadeja       8  CSK
4  devilliers      17  RCB
5  williamson      22   GT


**Pandas to handle missing values:**


1. Write a Pandas program to detect missing values of a given DataFrame.
Display True or False.

In [14]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit', np.nan, 'devilliers', 'williamson'], 'jersey': [7, 18, np.nan, 8, 17, np.nan ], 'team': ['CSK', 'RCB', 'MI', 'CSK', np.nan, np.nan]})
print(df)
print("\nMissing values of the DataFrame")
print(df.isna())

         name  jersey team
0       dhoni     7.0  CSK
1       virat    18.0  RCB
2       rohit     NaN   MI
3         NaN     8.0  CSK
4  devilliers    17.0  NaN
5  williamson     NaN  NaN

Missing values of the DataFrame
    name  jersey   team
0  False   False  False
1  False   False  False
2  False    True  False
3   True   False  False
4  False   False   True
5  False    True   True


2. Write a Pandas program to identify the column(s) of a given DataFrame
which have at least one missing value.

In [17]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit', np.nan, 'devilliers', 'williamson'], 'jersey': [7, 18, np.nan, 8, 17, np.nan ], 'team': ['CSK', 'RCB', 'MI', 'CSK', np.nan, np.nan]})
print(df)
print("\n Checking is there any any missing values of the DataFrame")
print(df.isna().any())

         name  jersey team
0       dhoni     7.0  CSK
1       virat    18.0  RCB
2       rohit     NaN   MI
3         NaN     8.0  CSK
4  devilliers    17.0  NaN
5  williamson     NaN  NaN

 Checking is there any any missing values of the DataFrame
name      True
jersey    True
team      True
dtype: bool


3. Write a Pandas program to count the number of missing values in each
column of a given DataFrame.


In [18]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit', np.nan, 'devilliers', 'williamson'], 'jersey': [7, 18, np.nan, 8, 17, np.nan ], 'team': ['CSK', 'RCB', 'MI', 'CSK', np.nan, np.nan]})
print(df)
print("\nCounting the no. of missing values of the DataFrame")
print(df.isna().sum())

         name  jersey team
0       dhoni     7.0  CSK
1       virat    18.0  RCB
2       rohit     NaN   MI
3         NaN     8.0  CSK
4  devilliers    17.0  NaN
5  williamson     NaN  NaN

Counting the no. of missing values of the DataFrame
name      1
jersey    2
team      2
dtype: int64


4. Write a Pandas program to find and replace the missing values in a given
DataFrame which do not have any valuable information.


In [20]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit', '?', 'devilliers', 'williamson'], 'jersey': [7, 18, '--', 8, 17, '?' ], 'team': ['CSK', 'RCB', 'MI', 'CSK', '?', np.nan]})
print(df)
print("\nReplacing the missing values of the DataFrame")
df1 = df.replace({"?": np.nan, "--": np.nan})
print(df1)

         name jersey team
0       dhoni      7  CSK
1       virat     18  RCB
2       rohit     --   MI
3           ?      8  CSK
4  devilliers     17    ?
5  williamson      ?  NaN

Replacing the missing values of the DataFrame
         name  jersey team
0       dhoni     7.0  CSK
1       virat    18.0  RCB
2       rohit     NaN   MI
3         NaN     8.0  CSK
4  devilliers    17.0  NaN
5  williamson     NaN  NaN


5. Write a Pandas program to drop the rows where at least one element is
missing in a given DataFrame.


In [22]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit', np.nan, 'devilliers', 'williamson'], 'jersey': [7, 18, np.nan, 8, 17, np.nan ], 'team': ['CSK', 'RCB', 'MI', 'CSK', np.nan, np.nan]})
print(df)
print("\nDrop the rows where at least one element is missing in a given DataFrame.")
df1 = df.dropna()
print(df1)

         name  jersey team
0       dhoni     7.0  CSK
1       virat    18.0  RCB
2       rohit     NaN   MI
3         NaN     8.0  CSK
4  devilliers    17.0  NaN
5  williamson     NaN  NaN

Drop the rows where at least one element is missing in a given DataFrame.
    name  jersey team
0  dhoni     7.0  CSK
1  virat    18.0  RCB


6. Write a Pandas program to drop the columns where at least one element is
missing in a given DataFrame.


In [25]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit', np.nan, 'devilliers', 'williamson'], 'jersey': [7, 18, np.nan, 8, 17, np.nan ], 'team': ['CSK', 'RCB', 'MI', 'CSK', np.nan, np.nan]})
print(df)
print("\nDrop the colums where at least one element is missing in a given DataFrame.")
df1 = df.dropna(axis = 'columns')
print(df1)

         name  jersey team
0       dhoni     7.0  CSK
1       virat    18.0  RCB
2       rohit     NaN   MI
3         NaN     8.0  CSK
4  devilliers    17.0  NaN
5  williamson     NaN  NaN

Drop the colums where at least one element is missing in a given DataFrame.
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5]


7. Write a Pandas program to drop the rows where all elements are missing in
a given DataFrame.

In [26]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit', np.nan, 'devilliers', 'williamson'], 'jersey': [7, 18, np.nan, 8, 17, np.nan ], 'team': ['CSK', 'RCB', 'MI', 'CSK', np.nan, np.nan]})
print(df)
print("\nDrop the rows where all element is missing in a given DataFrame.")
df1 = df.dropna(how = 'all')
print(df1)

         name  jersey team
0       dhoni     7.0  CSK
1       virat    18.0  RCB
2       rohit     NaN   MI
3         NaN     8.0  CSK
4  devilliers    17.0  NaN
5  williamson     NaN  NaN

Drop the rows where all element is missing in a given DataFrame.
         name  jersey team
0       dhoni     7.0  CSK
1       virat    18.0  RCB
2       rohit     NaN   MI
3         NaN     8.0  CSK
4  devilliers    17.0  NaN
5  williamson     NaN  NaN


8. Write a Pandas program to keep the rows with at least 2 NaN values in a
given DataFrame.

In [34]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit', np.nan, 'devilliers', 'williamson'], 'jersey': [7, 18, np.nan, 8, 17, np.nan ], 'team': ['CSK', 'RCB', 'MI', 'CSK', np.nan, np.nan]})
print(df)
print("\nKeep the rows with at least 2 NaN values in a given DataFrame.")
df1 = df.dropna(thresh = 2)
print(df1)

         name  jersey team
0       dhoni     7.0  CSK
1       virat    18.0  RCB
2       rohit     NaN   MI
3         NaN     8.0  CSK
4  devilliers    17.0  NaN
5  williamson     NaN  NaN

Keep the rows with at least 2 NaN values in a given DataFrame.
         name  jersey team
0       dhoni     7.0  CSK
1       virat    18.0  RCB
2       rohit     NaN   MI
3         NaN     8.0  CSK
4  devilliers    17.0  NaN


9. Write a Pandas program to drop those rows from a given DataFrame in
which specific columns have missing values.

In [33]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit', np.nan, 'devilliers', 'williamson'], 'jersey': [7, 18, np.nan, 8, 17, np.nan ], 'team': ['CSK', 'RCB', 'MI', 'CSK', np.nan, np.nan]})
print(df)
print("\nDrop those rows from a given DataFrame in which specific columns have missing values.")
df1 = df.dropna(subset = ['name', 'jersey'])
print(df1)

         name  jersey team
0       dhoni     7.0  CSK
1       virat    18.0  RCB
2       rohit     NaN   MI
3         NaN     8.0  CSK
4  devilliers    17.0  NaN
5  williamson     NaN  NaN

Drop those rows from a given DataFrame in which specific columns have missing values.
         name  jersey team
0       dhoni     7.0  CSK
1       virat    18.0  RCB
4  devilliers    17.0  NaN


10. Write a Pandas program to calculate the total number of missing values in
a DataFrame.

In [32]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit', np.nan, 'devilliers', 'williamson'], 'jersey': [7, 18, np.nan, 8, 17, np.nan ], 'team': ['CSK', 'RCB', 'MI', 'CSK', np.nan, np.nan]})
print(df)
print("\nCalculate the total number of missing values in a DataFrame.")
df1 = df.isna().sum().sum()
print(df1)

         name  jersey team
0       dhoni     7.0  CSK
1       virat    18.0  RCB
2       rohit     NaN   MI
3         NaN     8.0  CSK
4  devilliers    17.0  NaN
5  williamson     NaN  NaN

Calculate the total number of missing values in a DataFrame.
5


11. Write a Pandas program to replace NaNs with median or mean of the
specified columns in a given DataFrame.


In [35]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit', 'jadeja', 'devilliers', 'williamson'], 'jersey': [7, 18, np.nan, 8, 17, np.nan ], 'team': ['CSK', 'RCB', 'MI', 'CSK', 'RCB', 'GT']})
print(df)
print("\nReplacing Nans using median")
df['jersey'].fillna(df['jersey'].median(), inplace = True)
print(df)
print("\nReplacing Nans using median")
df['jersey'].fillna(df['jersey'].median(), inplace = True)
print(df)

         name  jersey team
0       dhoni     7.0  CSK
1       virat    18.0  RCB
2       rohit     NaN   MI
3      jadeja     8.0  CSK
4  devilliers    17.0  RCB
5  williamson     NaN   GT

Replacing Nans using median
         name  jersey team
0       dhoni     7.0  CSK
1       virat    18.0  RCB
2       rohit    12.5   MI
3      jadeja     8.0  CSK
4  devilliers    17.0  RCB
5  williamson    12.5   GT

Replacing Nans using median
         name  jersey team
0       dhoni     7.0  CSK
1       virat    18.0  RCB
2       rohit    12.5   MI
3      jadeja     8.0  CSK
4  devilliers    17.0  RCB
5  williamson    12.5   GT


12. Write a Pandas program to count the number of missing values of a
specified column in a given DataFrame.


In [40]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit', np.nan, 'devilliers', 'williamson'], 'jersey': [7, 18, np.nan, 8, 17, np.nan ], 'team': ['CSK', 'RCB', 'MI', 'CSK', np.nan, np.nan]})
print(df)
print("\nCounting the no. of missing values of the specified column in the DataFrame")
print(df.isna().sum())

         name  jersey team
0       dhoni     7.0  CSK
1       virat    18.0  RCB
2       rohit     NaN   MI
3         NaN     8.0  CSK
4  devilliers    17.0  NaN
5  williamson     NaN  NaN

Counting the no. of missing values of the specified column in the DataFrame
name      1
jersey    2
team      2
dtype: int64


13. Write a Pandas program to count the missing values in a given
DataFrame.


In [37]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit', np.nan, 'devilliers', 'williamson'], 'jersey': [7, 18, np.nan, 8, 17, np.nan ], 'team': ['CSK', 'RCB', 'MI', 'CSK', np.nan, np.nan]})
print(df)
print("\nCounting the no. of missing values of the DataFrame")
df1 = df.isnull().sum().sum()
print(df1)

         name  jersey team
0       dhoni     7.0  CSK
1       virat    18.0  RCB
2       rohit     NaN   MI
3         NaN     8.0  CSK
4  devilliers    17.0  NaN
5  williamson     NaN  NaN

Counting the no. of missing values of the DataFrame
5


14. Write a Pandas program to find the Indexes of missing values in a given
DataFrame.

In [38]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit', np.nan, 'devilliers', 'williamson'], 'jersey': [7, 18, np.nan, 8, 17, np.nan ], 'team': ['CSK', 'RCB', 'MI', 'CSK', np.nan, np.nan]})
print(df)
df1 = df['jersey'].isnull().to_numpy().nonzero()
print(df1)

         name  jersey team
0       dhoni     7.0  CSK
1       virat    18.0  RCB
2       rohit     NaN   MI
3         NaN     8.0  CSK
4  devilliers    17.0  NaN
5  williamson     NaN  NaN
(array([2, 5]),)


15. Write a Pandas program to replace NaNs with a single constant value in
specified columns in a DataFrame.

In [39]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'name': ['dhoni', 'virat', 'rohit', np.nan, 'devilliers', 'williamson'], 'jersey': [7, 18, np.nan, 8, 17, np.nan ], 'team': ['CSK', 'RCB', 'MI', 'CSK', np.nan, np.nan]})
print(df)
df1 = df['jersey'].fillna(0, inplace = False)
print(df1)

         name  jersey team
0       dhoni     7.0  CSK
1       virat    18.0  RCB
2       rohit     NaN   MI
3         NaN     8.0  CSK
4  devilliers    17.0  NaN
5  williamson     NaN  NaN
0     7.0
1    18.0
2     0.0
3     8.0
4    17.0
5     0.0
Name: jersey, dtype: float64
